### ISSUE TITLE
Configure timedatectl for systemd Hosts

### ISSUE THREAD

**Issue by naftulikay** [naftulikay/ansible-role-time#3]
#### TODO

 - [ ] Configure on `xenial`
 - [ ] Configure on `centos`
 - [ ] `timedatectl set-ntp true` must have been set and must be idempotent.
 - [ ] `timedatectl set-local-rtc false` must have been set and must be idempotent.
